# Generated by Django 3.1.3 on 2020-11-27 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('classe', models.IntegerField(choices=[(1, 'Canino'), (2, 'Felino')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ONG', to=settings.AUTH_USER_MODEL)),
                ('padrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PADRINHO', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
