# Generated by Django 3.1.3 on 2020-12-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0003_animal_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='name',
            new_name='nome',
        ),
    ]
