# Generated by Django 3.1.3 on 2020-12-01 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paws', '0004_auto_20201201_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='padrinho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PADRINHO', to=settings.AUTH_USER_MODEL),
        ),
    ]
